### ISSUE TITLE
ToDo's in sync unit tests in at_server

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#1125]
This is a base git issue to list out all the refactoring/enhancements that are identified during the analysis in the sync unit tests in the at_server.

**Things to refactor**

- [x] Expose the capacity of SyncBuffer to write unit tests. The changes are completed and pushed in the following PR: https://github.com/atsign-foundation/at_server/pull/1098
- [x]  Add validation to check if the key is Invalid before adding it to the sync response
- [x] The version, createdAt, createdBy fields in the AtMetadata are not populated correctly. https://github.com/atsign-foundation/at_server/issues/1126

**Things to discuss**
- [x] Can we skip the expired keys (keys whose TTL is met) but not deleted from the Keystore in the sync response?
- [x] When the batch request contains a key with CommitOp.Delete and the key does not exist in the cloud secondary, Can we return an exception back?

**Comment by sitaram-kalluri** [comment]
Should we return an exception on the delete operation when a key does not exist in the cloud secondary? The changes related to throwing an exception on the deletion of the non-existent key are reverted due to the side effects in the sync service. Refer to the following git issue: https://github.com/atsign-foundation/at_server/pull/1022

**Comment by gkc** [comment]
No we discussed this in architecture calls and decided we should not

**Comment by sitaram-kalluri** [comment]
All the items in the "Things to refactor section" are completed and changes are merged into the trunk.

The pending item in this is to discuss the following article: Can we skip the expired keys (keys whose TTL is met) but not deleted from the Keystore in the sync response?

**Comment by sitaram-kalluri** [comment]
As discussed in the arch call, we are not implementing the change of skipping expired keys
