### ISSUE TITLE
[Tracker] Design for persistence enhancements

### ISSUE THREAD

**Issue by VJag** [atsign-foundation/at_server#1429]
### Is your feature request related to a problem? Please describe.

We want to enhance the following in the persistence layer of the secondary server:

```[tasklist]
### Tasks
- [ ] Comeup with a design to prevent commitlog growing infinitely when keys are created and deleted
- [ ] Analyze advantages of persisting (in a hive box) what we store in commitlog ache map today
- [ ] Analyze readiness to replace the persistence store from Hive to any other store
```

### Describe the solution you'd like

Perform the analysis and produce design docs
