### ISSUE TITLE
Enhance the functional tests

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#505]
Lead: @gkc 

Enhance the functional tests

- [x] Fix the issues and merge the functional tests PR to Trunk https://github.com/atsign-foundation/at_server/pull/245
- [x] pkam between secondaries test
- [x]  Updating same key multiple times #535 
- [x]  Multiple keys at the same time #535 
- [x] Latency Tests #535 
- [x] TTR & Cachebility Tests #535
- [x] Repeated Auth #535 
- [x] TTL, TTB tests #535

**Comment by gkc** [comment]
@kalluriramkumar @VJag @murali-shris let's invest some time in scoping this a bit better; we didn't estimate today but I'm going to estimate 5 SP for this for now

**Comment by gkc** [comment]
Was a little more than 5SP (across the team) this sprint; expect same again next sprint, maybe more

**Comment by gkc** [comment]
There are gaps in functional tests in at_client_sdk and end to end tests in at_server. We need to continue to work to close those gaps. See also [this doc](https://docs.google.com/spreadsheets/d/1cpjRlu81-LBDma6edlHTwvpbI9YQG-berDYaII-0Esw/edit#gid=0) that @purnimavenkatasubbu has created

**Comment by purnimavenkatasubbu** [comment]
Covered the tests which are part of [this doc](https://docs.google.com/spreadsheets/d/1cpjRlu81-LBDma6edlHTwvpbI9YQG-berDYaII-0Esw/edit#gid=0)  in the following [PR](https://github.com/atsign-foundation/at_server/pull/535)

Added a new ticket for tests that need a config change.

**Comment by murali-shris** [comment]
added 1SP for merging PR and closing the issue

**Comment by purnimavenkatasubbu** [comment]
PR is merged to trunk.
