### ISSUE TITLE
NSS++    :  Notification sub system improvements

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#546]
**Is your feature request related to a problem? Please describe.**
Notification Sub System is designed to work in a certain way. But now seems to be the time to look at some of the decisions we made and improve them for the better.

**Describe the solution you'd like**
In the comment below

**Describe alternatives you've considered**
NA

**Additional context**
The focus of this task is to capture what we want to improve in NSS.  it would be better to track actual implementation using a differnt ticket.

**Comment by VJag** [comment]
My notes on this task are captured here:
https://docs.google.com/document/d/14sFNMjewgQsQde0qoRU37WctBXSQnfOvgOJLrfphzaA/edit?usp=sharing

**Comment by VJag** [comment]
Following tickets address the improvements we want to perform in NSS: (Will update the tickets)

- [ ] https://github.com/atsign-foundation/at_server/issues/589
- [x] [New encryption and decryption on notify with key](https://github.com/atsign-foundation/at_client_sdk/issues/436)
- [x] Move decryption of notifications from apps to SDK
- [x] [Constructs to delete notifications before expiry and keep the server light](https://github.com/atsign-foundation/at_server/issues/610)
    notify:expire/delete <id> 
- [x] [Ticket that increases the timeout](https://github.com/atsign-foundation/at_server/issues/590)
- [x] [Same notification access the sender and the recipient](https://github.com/atsign-foundation/at_server/issues/592)
- [x] [Generate id on the client and Update syntax to accommodate the id...](https://github.com/atsign-foundation/at_client_sdk/issues/451)
- [ ] Option to not to autoNotify certain shared key changes. (This use case is important for those scenarios where same key gets updated a million times and the recipient and sender end up saving million notifications for them which is not required and makes the secondary slow. fsync solves this problem in a different way)

**Comment by sitaram-kalluri** [comment]
The above tasks marked are completed and changes need to be merged and published. Carry over to publish the changes. 3SP pending work

**Comment by murali-shris** [comment]
@kalluriramkumar please create tasks for pending work
